import {
  Project,
  Sprite,
} from "https://unpkg.com/leopard@^1/dist/index.esm.js";

import Stage from "./Stage/Stage.js";
import Title from "./Title/Title.js";
import TierList from "./TierList/TierList.js";
import Hominid from "./Hominid/Hominid.js";
import StatsHominid from "./StatsHominid/StatsHominid.js";
import Ant from "./Ant/Ant.js";
import StatsAnt from "./StatsAnt/StatsAnt.js";
import FelineCat from "./FelineCat/FelineCat.js";
import StatsDomesticFeline from "./StatsDomesticFeline/StatsDomesticFeline.js";
import Cetatian from "./Cetatian/Cetatian.js";
import StatsCetatian from "./StatsCetatian/StatsCetatian.js";
import Pachyderm from "./Pachyderm/Pachyderm.js";
import StatsPachyderm from "./StatsPachyderm/StatsPachyderm.js";
import CanineDog from "./CanineDog/CanineDog.js";
import StatsDomesticCanine from "./StatsDomesticCanine/StatsDomesticCanine.js";
import Crocodilian from "./Crocodilian/Crocodilian.js";
import StatsCrocodilian from "./StatsCrocodilian/StatsCrocodilian.js";
import Shark from "./Shark/Shark.js";
import StatsShark from "./StatsShark/StatsShark.js";
import Bear from "./Bear/Bear.js";
import StatsUrsid from "./StatsUrsid/StatsUrsid.js";
import Simian from "./Simian/Simian.js";
import StatsSimian from "./StatsSimian/StatsSimian.js";
import Cephalopod from "./Cephalopod/Cephalopod.js";
import StatsCephalopod from "./StatsCephalopod/StatsCephalopod.js";
import Lion from "./Lion/Lion.js";
import StatsLion from "./StatsLion/StatsLion.js";
import Lupine from "./Lupine/Lupine.js";
import StatsWolf from "./StatsWolf/StatsWolf.js";
import Corvid from "./Corvid/Corvid.js";
import StatsCorvid from "./StatsCorvid/StatsCorvid.js";
import Mustelid from "./Mustelid/Mustelid.js";
import StatsMustelid from "./StatsMustelid/StatsMustelid.js";
import Caprinan from "./Caprinan/Caprinan.js";
import StatsCaprinan from "./StatsCaprinan/StatsCaprinan.js";
import Raptor from "./Raptor/Raptor.js";
import StatsRaptor from "./StatsRaptor/StatsRaptor.js";
import Rodent from "./Rodent/Rodent.js";
import StatsRodent from "./StatsRodent/StatsRodent.js";
import Elapid from "./Elapid/Elapid.js";
import StatsElapid from "./StatsElapid/StatsElapid.js";
import Vulpid from "./Vulpid/Vulpid.js";
import StatsVulpid from "./StatsVulpid/StatsVulpid.js";
import Iguana from "./Iguana/Iguana.js";
import StatsIguana from "./StatsIguana/StatsIguana.js";
import Bat from "./Bat/Bat.js";
import StatsBat from "./StatsBat/StatsBat.js";
import Pinniped from "./Pinniped/Pinniped.js";
import StatsPinnipeds from "./StatsPinnipeds/StatsPinnipeds.js";
import Racoon from "./Racoon/Racoon.js";
import StatsProcynonid from "./StatsProcynonid/StatsProcynonid.js";
import Cervid from "./Cervid/Cervid.js";
import StatsCervid from "./StatsCervid/StatsCervid.js";
import Crustacean from "./Crustacean/Crustacean.js";
import StatsCrab from "./StatsCrab/StatsCrab.js";
import Tortoise from "./Tortoise/Tortoise.js";
import StatsTortoise from "./StatsTortoise/StatsTortoise.js";
import Lizard from "./Lizard/Lizard.js";
import StatsLizard from "./StatsLizard/StatsLizard.js";
import Rhinoceros from "./Rhinoceros/Rhinoceros.js";
import StatsRhinoceros from "./StatsRhinoceros/StatsRhinoceros.js";
import Goose from "./Goose/Goose.js";
import StatsGoose from "./StatsGoose/StatsGoose.js";
import Coulbrid from "./Coulbrid/Coulbrid.js";
import StatsCoulbrid from "./StatsCoulbrid/StatsCoulbrid.js";
import Salmon from "./Salmon/Salmon.js";
import StatsSalmon from "./StatsSalmon/StatsSalmon.js";
import Canine from "./Canine/Canine.js";
import StatsCoyote from "./StatsCoyote/StatsCoyote.js";
import Ostrich from "./Ostrich/Ostrich.js";
import StatsOstrich from "./StatsOstrich/StatsOstrich.js";
import Pigeon from "./Pigeon/Pigeon.js";
import StatsPigeon from "./StatsPigeon/StatsPigeon.js";
import Cheetah from "./Cheetah/Cheetah.js";
import StatsCheetah from "./StatsCheetah/StatsCheetah.js";
import MolaMola from "./MolaMola/MolaMola.js";
import StatsSunfish from "./StatsSunfish/StatsSunfish.js";
import Marsupial from "./Marsupial/Marsupial.js";
import StatsMarsupial from "./StatsMarsupial/StatsMarsupial.js";
import Frog from "./Frog/Frog.js";
import StatsFrog from "./StatsFrog/StatsFrog.js";
import Prosimian from "./Prosimian/Prosimian.js";
import StatsProsimian from "./StatsProsimian/StatsProsimian.js";
import Sloth from "./Sloth/Sloth.js";
import StatsSloth from "./StatsSloth/StatsSloth.js";
import Tardigrade from "./Tardigrade/Tardigrade.js";
import StatsTardigrade from "./StatsTardigrade/StatsTardigrade.js";
import Square from "./Square/Square.js";
import Stats from "./Stats/Stats.js";
import Oops from "./Oops/Oops.js";
import Oops2 from "./Oops2/Oops2.js";
import Icons from "./Icons/Icons.js";
import Cursor from "./Cursor/Cursor.js";
import Bluefishingpole from "./Bluefishingpole/Bluefishingpole.js";
import Sprite1 from "./Sprite1/Sprite1.js";
import ScreenShot20210402At2 from "./ScreenShot20210402At2/ScreenShot20210402At2.js";

const stage = new Stage({ costumeNumber: 1 });

const sprites = {
  Title: new Title({
    x: 0,
    y: 0,
    direction: 90,
    rotationStyle: Sprite.RotationStyle.ALL_AROUND,
    costumeNumber: 1,
    size: 100,
    visible: false,
    layerOrder: 1,
  }),
  TierList: new TierList({
    x: 0,
    y: 10,
    direction: 90,
    rotationStyle: Sprite.RotationStyle.ALL_AROUND,
    costumeNumber: 1,
    size: 135,
    visible: true,
    layerOrder: 45,
  }),
  Hominid: new Hominid({
    x: -172,
    y: 116,
    direction: 90,
    rotationStyle: Sprite.RotationStyle.ALL_AROUND,
    costumeNumber: 1,
    size: 100,
    visible: true,
    layerOrder: 93,
  }),
  StatsHominid: new StatsHominid({
    x: 0,
    y: 0,
    direction: 90,
    rotationStyle: Sprite.RotationStyle.ALL_AROUND,
    costumeNumber: 1,
    size: 100,
    visible: false,
    layerOrder: 19,
  }),
  Ant: new Ant({
    x: -112,
    y: 116,
    direction: 90,
    rotationStyle: Sprite.RotationStyle.ALL_AROUND,
    costumeNumber: 1,
    size: 100,
    visible: true,
    layerOrder: 94,
  }),
  StatsAnt: new StatsAnt({
    x: 0,
    y: 0,
    direction: 90,
    rotationStyle: Sprite.RotationStyle.ALL_AROUND,
    costumeNumber: 1,
    size: 100,
    visible: false,
    layerOrder: 9,
  }),
  FelineCat: new FelineCat({
    x: -52,
    y: 116,
    direction: 90,
    rotationStyle: Sprite.RotationStyle.ALL_AROUND,
    costumeNumber: 1,
    size: 100,
    visible: true,
    layerOrder: 64,
  }),
  StatsDomesticFeline: new StatsDomesticFeline({
    x: 0,
    y: 0,
    direction: 90,
    rotationStyle: Sprite.RotationStyle.ALL_AROUND,
    costumeNumber: 1,
    size: 100,
    visible: false,
    layerOrder: 21,
  }),
  Cetatian: new Cetatian({
    x: 8,
    y: 116,
    direction: 90,
    rotationStyle: Sprite.RotationStyle.ALL_AROUND,
    costumeNumber: 1,
    size: 100,
    visible: true,
    layerOrder: 63,
  }),
  StatsCetatian: new StatsCetatian({
    x: 0,
    y: 0,
    direction: 90,
    rotationStyle: Sprite.RotationStyle.ALL_AROUND,
    costumeNumber: 1,
    size: 100,
    visible: false,
    layerOrder: 38,
  }),
  Pachyderm: new Pachyderm({
    x: 68,
    y: 116,
    direction: 90,
    rotationStyle: Sprite.RotationStyle.ALL_AROUND,
    costumeNumber: 1,
    size: 100,
    visible: true,
    layerOrder: 62,
  }),
  StatsPachyderm: new StatsPachyderm({
    x: 0,
    y: 0,
    direction: 90,
    rotationStyle: Sprite.RotationStyle.ALL_AROUND,
    costumeNumber: 1,
    size: 100,
    visible: false,
    layerOrder: 20,
  }),
  CanineDog: new CanineDog({
    x: 128,
    y: 116,
    direction: 90,
    rotationStyle: Sprite.RotationStyle.ALL_AROUND,
    costumeNumber: 1,
    size: 100,
    visible: true,
    layerOrder: 61,
  }),
  StatsDomesticCanine: new StatsDomesticCanine({
    x: 0,
    y: 0,
    direction: 90,
    rotationStyle: Sprite.RotationStyle.ALL_AROUND,
    costumeNumber: 1,
    size: 100,
    visible: false,
    layerOrder: 31,
  }),
  Crocodilian: new Crocodilian({
    x: 188,
    y: 116,
    direction: 90,
    rotationStyle: Sprite.RotationStyle.ALL_AROUND,
    costumeNumber: 1,
    size: 100,
    visible: true,
    layerOrder: 60,
  }),
  StatsCrocodilian: new StatsCrocodilian({
    x: 0,
    y: 0,
    direction: 90,
    rotationStyle: Sprite.RotationStyle.ALL_AROUND,
    costumeNumber: 1,
    size: 100,
    visible: false,
    layerOrder: 10,
  }),
  Shark: new Shark({
    x: -172,
    y: 66,
    direction: 90,
    rotationStyle: Sprite.RotationStyle.ALL_AROUND,
    costumeNumber: 1,
    size: 100,
    visible: true,
    layerOrder: 88,
  }),
  StatsShark: new StatsShark({
    x: 0,
    y: 0,
    direction: 90,
    rotationStyle: Sprite.RotationStyle.ALL_AROUND,
    costumeNumber: 1,
    size: 100,
    visible: false,
    layerOrder: 30,
  }),
  Bear: new Bear({
    x: -112,
    y: 66,
    direction: 90,
    rotationStyle: Sprite.RotationStyle.ALL_AROUND,
    costumeNumber: 1,
    size: 100,
    visible: true,
    layerOrder: 92,
  }),
  StatsUrsid: new StatsUrsid({
    x: 0,
    y: 0,
    direction: 90,
    rotationStyle: Sprite.RotationStyle.ALL_AROUND,
    costumeNumber: 1,
    size: 100,
    visible: false,
    layerOrder: 11,
  }),
  Simian: new Simian({
    x: -52,
    y: 66,
    direction: 90,
    rotationStyle: Sprite.RotationStyle.ALL_AROUND,
    costumeNumber: 1,
    size: 100,
    visible: true,
    layerOrder: 85,
  }),
  StatsSimian: new StatsSimian({
    x: 0,
    y: 0,
    direction: 90,
    rotationStyle: Sprite.RotationStyle.ALL_AROUND,
    costumeNumber: 1,
    size: 100,
    visible: false,
    layerOrder: 8,
  }),
  Cephalopod: new Cephalopod({
    x: 8,
    y: 66,
    direction: 90,
    rotationStyle: Sprite.RotationStyle.ALL_AROUND,
    costumeNumber: 1,
    size: 100,
    visible: true,
    layerOrder: 84,
  }),
  StatsCephalopod: new StatsCephalopod({
    x: 0,
    y: 0,
    direction: 90,
    rotationStyle: Sprite.RotationStyle.ALL_AROUND,
    costumeNumber: 1,
    size: 100,
    visible: false,
    layerOrder: 28,
  }),
  Lion: new Lion({
    x: 68,
    y: 66,
    direction: 90,
    rotationStyle: Sprite.RotationStyle.ALL_AROUND,
    costumeNumber: 1,
    size: 100,
    visible: true,
    layerOrder: 91,
  }),
  StatsLion: new StatsLion({
    x: 0,
    y: 0,
    direction: 90,
    rotationStyle: Sprite.RotationStyle.ALL_AROUND,
    costumeNumber: 1,
    size: 100,
    visible: false,
    layerOrder: 34,
  }),
  Lupine: new Lupine({
    x: 128,
    y: 66,
    direction: 90,
    rotationStyle: Sprite.RotationStyle.ALL_AROUND,
    costumeNumber: 1,
    size: 100,
    visible: true,
    layerOrder: 90,
  }),
  StatsWolf: new StatsWolf({
    x: 0,
    y: 0,
    direction: 90,
    rotationStyle: Sprite.RotationStyle.ALL_AROUND,
    costumeNumber: 1,
    size: 100,
    visible: false,
    layerOrder: 41,
  }),
  Corvid: new Corvid({
    x: 188,
    y: 66,
    direction: 90,
    rotationStyle: Sprite.RotationStyle.ALL_AROUND,
    costumeNumber: 1,
    size: 100,
    visible: true,
    layerOrder: 86,
  }),
  StatsCorvid: new StatsCorvid({
    x: 0,
    y: 0,
    direction: 90,
    rotationStyle: Sprite.RotationStyle.ALL_AROUND,
    costumeNumber: 1,
    size: 100,
    visible: false,
    layerOrder: 37,
  }),
  Mustelid: new Mustelid({
    x: -172,
    y: 16,
    direction: 90,
    rotationStyle: Sprite.RotationStyle.ALL_AROUND,
    costumeNumber: 1,
    size: 100,
    visible: true,
    layerOrder: 70,
  }),
  StatsMustelid: new StatsMustelid({
    x: 0,
    y: 0,
    direction: 90,
    rotationStyle: Sprite.RotationStyle.ALL_AROUND,
    costumeNumber: 1,
    size: 100,
    visible: false,
    layerOrder: 6,
  }),
  Caprinan: new Caprinan({
    x: -112,
    y: 16,
    direction: 90,
    rotationStyle: Sprite.RotationStyle.ALL_AROUND,
    costumeNumber: 1,
    size: 100,
    visible: true,
    layerOrder: 69,
  }),
  StatsCaprinan: new StatsCaprinan({
    x: 0,
    y: 0,
    direction: 90,
    rotationStyle: Sprite.RotationStyle.ALL_AROUND,
    costumeNumber: 1,
    size: 100,
    visible: false,
    layerOrder: 12,
  }),
  Raptor: new Raptor({
    x: -52,
    y: 16,
    direction: 90,
    rotationStyle: Sprite.RotationStyle.ALL_AROUND,
    costumeNumber: 1,
    size: 100,
    visible: true,
    layerOrder: 68,
  }),
  StatsRaptor: new StatsRaptor({
    x: 0,
    y: 0,
    direction: 90,
    rotationStyle: Sprite.RotationStyle.ALL_AROUND,
    costumeNumber: 1,
    size: 100,
    visible: false,
    layerOrder: 7,
  }),
  Rodent: new Rodent({
    x: 8,
    y: 16,
    direction: 90,
    rotationStyle: Sprite.RotationStyle.ALL_AROUND,
    costumeNumber: 1,
    size: 100,
    visible: true,
    layerOrder: 66,
  }),
  StatsRodent: new StatsRodent({
    x: 0,
    y: 0,
    direction: 90,
    rotationStyle: Sprite.RotationStyle.ALL_AROUND,
    costumeNumber: 1,
    size: 100,
    visible: false,
    layerOrder: 26,
  }),
  Elapid: new Elapid({
    x: 68,
    y: 16,
    direction: 90,
    rotationStyle: Sprite.RotationStyle.ALL_AROUND,
    costumeNumber: 1,
    size: 100,
    visible: true,
    layerOrder: 67,
  }),
  StatsElapid: new StatsElapid({
    x: 0,
    y: 0,
    direction: 90,
    rotationStyle: Sprite.RotationStyle.ALL_AROUND,
    costumeNumber: 1,
    size: 100,
    visible: false,
    layerOrder: 5,
  }),
  Vulpid: new Vulpid({
    x: 128,
    y: 16,
    direction: 90,
    rotationStyle: Sprite.RotationStyle.ALL_AROUND,
    costumeNumber: 1,
    size: 100,
    visible: true,
    layerOrder: 58,
  }),
  StatsVulpid: new StatsVulpid({
    x: 0,
    y: 0,
    direction: 90,
    rotationStyle: Sprite.RotationStyle.ALL_AROUND,
    costumeNumber: 1,
    size: 100,
    visible: false,
    layerOrder: 47,
  }),
  Iguana: new Iguana({
    x: 188,
    y: 16,
    direction: 90,
    rotationStyle: Sprite.RotationStyle.ALL_AROUND,
    costumeNumber: 1,
    size: 100,
    visible: true,
    layerOrder: 59,
  }),
  StatsIguana: new StatsIguana({
    x: 0,
    y: 0,
    direction: 90,
    rotationStyle: Sprite.RotationStyle.ALL_AROUND,
    costumeNumber: 1,
    size: 100,
    visible: false,
    layerOrder: 25,
  }),
  Bat: new Bat({
    x: -172,
    y: -34,
    direction: 90,
    rotationStyle: Sprite.RotationStyle.ALL_AROUND,
    costumeNumber: 1,
    size: 100,
    visible: true,
    layerOrder: 80,
  }),
  StatsBat: new StatsBat({
    x: 0,
    y: 0,
    direction: 90,
    rotationStyle: Sprite.RotationStyle.ALL_AROUND,
    costumeNumber: 1,
    size: 100,
    visible: false,
    layerOrder: 14,
  }),
  Pinniped: new Pinniped({
    x: -112,
    y: -34,
    direction: 90,
    rotationStyle: Sprite.RotationStyle.ALL_AROUND,
    costumeNumber: 1,
    size: 100,
    visible: true,
    layerOrder: 81,
  }),
  StatsPinnipeds: new StatsPinnipeds({
    x: 0,
    y: 0,
    direction: 90,
    rotationStyle: Sprite.RotationStyle.ALL_AROUND,
    costumeNumber: 1,
    size: 100,
    visible: false,
    layerOrder: 36,
  }),
  Racoon: new Racoon({
    x: -52,
    y: -34,
    direction: 90,
    rotationStyle: Sprite.RotationStyle.ALL_AROUND,
    costumeNumber: 1,
    size: 100,
    visible: true,
    layerOrder: 54,
  }),
  StatsProcynonid: new StatsProcynonid({
    x: 0,
    y: 0,
    direction: 90,
    rotationStyle: Sprite.RotationStyle.ALL_AROUND,
    costumeNumber: 1,
    size: 100,
    visible: false,
    layerOrder: 15,
  }),
  Cervid: new Cervid({
    x: 8,
    y: -34,
    direction: 90,
    rotationStyle: Sprite.RotationStyle.ALL_AROUND,
    costumeNumber: 1,
    size: 100,
    visible: true,
    layerOrder: 82,
  }),
  StatsCervid: new StatsCervid({
    x: 0,
    y: 0,
    direction: 90,
    rotationStyle: Sprite.RotationStyle.ALL_AROUND,
    costumeNumber: 1,
    size: 100,
    visible: false,
    layerOrder: 22,
  }),
  Crustacean: new Crustacean({
    x: 68,
    y: -34,
    direction: 90,
    rotationStyle: Sprite.RotationStyle.ALL_AROUND,
    costumeNumber: 1,
    size: 100,
    visible: true,
    layerOrder: 55,
  }),
  StatsCrab: new StatsCrab({
    x: 0,
    y: 0,
    direction: 90,
    rotationStyle: Sprite.RotationStyle.ALL_AROUND,
    costumeNumber: 1,
    size: 100,
    visible: false,
    layerOrder: 16,
  }),
  Tortoise: new Tortoise({
    x: 128,
    y: -34,
    direction: 90,
    rotationStyle: Sprite.RotationStyle.ALL_AROUND,
    costumeNumber: 1,
    size: 100,
    visible: true,
    layerOrder: 83,
  }),
  StatsTortoise: new StatsTortoise({
    x: 0,
    y: 0,
    direction: 90,
    rotationStyle: Sprite.RotationStyle.ALL_AROUND,
    costumeNumber: 1,
    size: 100,
    visible: false,
    layerOrder: 32,
  }),
  Lizard: new Lizard({
    x: 188,
    y: -34,
    direction: 90,
    rotationStyle: Sprite.RotationStyle.ALL_AROUND,
    costumeNumber: 1,
    size: 100,
    visible: true,
    layerOrder: 56,
  }),
  StatsLizard: new StatsLizard({
    x: 0,
    y: 0,
    direction: 90,
    rotationStyle: Sprite.RotationStyle.ALL_AROUND,
    costumeNumber: 1,
    size: 100,
    visible: false,
    layerOrder: 4,
  }),
  Rhinoceros: new Rhinoceros({
    x: -172,
    y: -83,
    direction: 90,
    rotationStyle: Sprite.RotationStyle.ALL_AROUND,
    costumeNumber: 1,
    size: 100,
    visible: true,
    layerOrder: 89,
  }),
  StatsRhinoceros: new StatsRhinoceros({
    x: 0,
    y: 0,
    direction: 90,
    rotationStyle: Sprite.RotationStyle.ALL_AROUND,
    costumeNumber: 1,
    size: 100,
    visible: false,
    layerOrder: 24,
  }),
  Goose: new Goose({
    x: -112,
    y: -83,
    direction: 90,
    rotationStyle: Sprite.RotationStyle.ALL_AROUND,
    costumeNumber: 1,
    size: 100,
    visible: true,
    layerOrder: 71,
  }),
  StatsGoose: new StatsGoose({
    x: 0,
    y: 0,
    direction: 90,
    rotationStyle: Sprite.RotationStyle.ALL_AROUND,
    costumeNumber: 1,
    size: 100,
    visible: false,
    layerOrder: 23,
  }),
  Coulbrid: new Coulbrid({
    x: -52,
    y: -83,
    direction: 90,
    rotationStyle: Sprite.RotationStyle.ALL_AROUND,
    costumeNumber: 1,
    size: 100,
    visible: true,
    layerOrder: 72,
  }),
  StatsCoulbrid: new StatsCoulbrid({
    x: 0,
    y: 0,
    direction: 90,
    rotationStyle: Sprite.RotationStyle.ALL_AROUND,
    costumeNumber: 1,
    size: 100,
    visible: false,
    layerOrder: 43,
  }),
  Salmon: new Salmon({
    x: 8,
    y: -83,
    direction: 90,
    rotationStyle: Sprite.RotationStyle.ALL_AROUND,
    costumeNumber: 1,
    size: 100,
    visible: true,
    layerOrder: 65,
  }),
  StatsSalmon: new StatsSalmon({
    x: 0,
    y: 0,
    direction: 90,
    rotationStyle: Sprite.RotationStyle.ALL_AROUND,
    costumeNumber: 1,
    size: 100,
    visible: false,
    layerOrder: 27,
  }),
  Canine: new Canine({
    x: 68,
    y: -83,
    direction: 90,
    rotationStyle: Sprite.RotationStyle.ALL_AROUND,
    costumeNumber: 1,
    size: 100,
    visible: true,
    layerOrder: 57,
  }),
  StatsCoyote: new StatsCoyote({
    x: 0,
    y: 0,
    direction: 90,
    rotationStyle: Sprite.RotationStyle.ALL_AROUND,
    costumeNumber: 1,
    size: 100,
    visible: false,
    layerOrder: 35,
  }),
  Ostrich: new Ostrich({
    x: 128,
    y: -83,
    direction: 90,
    rotationStyle: Sprite.RotationStyle.ALL_AROUND,
    costumeNumber: 1,
    size: 100,
    visible: true,
    layerOrder: 73,
  }),
  StatsOstrich: new StatsOstrich({
    x: 0,
    y: 0,
    direction: 90,
    rotationStyle: Sprite.RotationStyle.ALL_AROUND,
    costumeNumber: 1,
    size: 100,
    visible: false,
    layerOrder: 39,
  }),
  Pigeon: new Pigeon({
    x: 188,
    y: -83,
    direction: 90,
    rotationStyle: Sprite.RotationStyle.ALL_AROUND,
    costumeNumber: 1,
    size: 100,
    visible: true,
    layerOrder: 53,
  }),
  StatsPigeon: new StatsPigeon({
    x: 0,
    y: 0,
    direction: 90,
    rotationStyle: Sprite.RotationStyle.ALL_AROUND,
    costumeNumber: 1,
    size: 100,
    visible: false,
    layerOrder: 40,
  }),
  Cheetah: new Cheetah({
    x: -172,
    y: -134,
    direction: 90,
    rotationStyle: Sprite.RotationStyle.ALL_AROUND,
    costumeNumber: 1,
    size: 100,
    visible: true,
    layerOrder: 74,
  }),
  StatsCheetah: new StatsCheetah({
    x: 0,
    y: 0,
    direction: 90,
    rotationStyle: Sprite.RotationStyle.ALL_AROUND,
    costumeNumber: 1,
    size: 100,
    visible: false,
    layerOrder: 13,
  }),
  MolaMola: new MolaMola({
    x: -112,
    y: -134,
    direction: 90,
    rotationStyle: Sprite.RotationStyle.ALL_AROUND,
    costumeNumber: 1,
    size: 100,
    visible: true,
    layerOrder: 76,
  }),
  StatsSunfish: new StatsSunfish({
    x: 0,
    y: 0,
    direction: 90,
    rotationStyle: Sprite.RotationStyle.ALL_AROUND,
    costumeNumber: 1,
    size: 100,
    visible: false,
    layerOrder: 18,
  }),
  Marsupial: new Marsupial({
    x: -52,
    y: -134,
    direction: 90,
    rotationStyle: Sprite.RotationStyle.ALL_AROUND,
    costumeNumber: 1,
    size: 100,
    visible: true,
    layerOrder: 77,
  }),
  StatsMarsupial: new StatsMarsupial({
    x: 0,
    y: 0,
    direction: 90,
    rotationStyle: Sprite.RotationStyle.ALL_AROUND,
    costumeNumber: 1,
    size: 100,
    visible: false,
    layerOrder: 42,
  }),
  Frog: new Frog({
    x: 8,
    y: -134,
    direction: 90,
    rotationStyle: Sprite.RotationStyle.ALL_AROUND,
    costumeNumber: 1,
    size: 100,
    visible: true,
    layerOrder: 75,
  }),
  StatsFrog: new StatsFrog({
    x: 0,
    y: 0,
    direction: 90,
    rotationStyle: Sprite.RotationStyle.ALL_AROUND,
    costumeNumber: 1,
    size: 100,
    visible: false,
    layerOrder: 17,
  }),
  Prosimian: new Prosimian({
    x: 68,
    y: -134,
    direction: 90,
    rotationStyle: Sprite.RotationStyle.ALL_AROUND,
    costumeNumber: 1,
    size: 100,
    visible: true,
    layerOrder: 87,
  }),
  StatsProsimian: new StatsProsimian({
    x: 0,
    y: 0,
    direction: 90,
    rotationStyle: Sprite.RotationStyle.ALL_AROUND,
    costumeNumber: 1,
    size: 100,
    visible: false,
    layerOrder: 33,
  }),
  Sloth: new Sloth({
    x: 128,
    y: -134,
    direction: 90,
    rotationStyle: Sprite.RotationStyle.ALL_AROUND,
    costumeNumber: 1,
    size: 100,
    visible: true,
    layerOrder: 79,
  }),
  StatsSloth: new StatsSloth({
    x: 0,
    y: 0,
    direction: 90,
    rotationStyle: Sprite.RotationStyle.ALL_AROUND,
    costumeNumber: 1,
    size: 100,
    visible: false,
    layerOrder: 44,
  }),
  Tardigrade: new Tardigrade({
    x: 188,
    y: -134,
    direction: 90,
    rotationStyle: Sprite.RotationStyle.ALL_AROUND,
    costumeNumber: 1,
    size: 100,
    visible: true,
    layerOrder: 78,
  }),
  StatsTardigrade: new StatsTardigrade({
    x: 0,
    y: 0,
    direction: 90,
    rotationStyle: Sprite.RotationStyle.ALL_AROUND,
    costumeNumber: 1,
    size: 100,
    visible: false,
    layerOrder: 29,
  }),
  Square: new Square({
    x: 94.04476312604224,
    y: -28.43601503910743,
    direction: 90,
    rotationStyle: Sprite.RotationStyle.ALL_AROUND,
    costumeNumber: 1,
    size: 100,
    visible: false,
    layerOrder: 48,
  }),
  Stats: new Stats({
    x: 0,
    y: 0,
    direction: 90,
    rotationStyle: Sprite.RotationStyle.ALL_AROUND,
    costumeNumber: 1,
    size: 100,
    visible: false,
    layerOrder: 46,
  }),
  Oops: new Oops({
    x: 0,
    y: 0,
    direction: 90,
    rotationStyle: Sprite.RotationStyle.ALL_AROUND,
    costumeNumber: 1,
    size: 100,
    visible: false,
    layerOrder: 2,
  }),
  Oops2: new Oops2({
    x: 0,
    y: 0,
    direction: 90,
    rotationStyle: Sprite.RotationStyle.ALL_AROUND,
    costumeNumber: 1,
    size: 100,
    visible: false,
    layerOrder: 3,
  }),
  Icons: new Icons({
    x: 14.472641080528437,
    y: 34.4022555153528,
    direction: 90,
    rotationStyle: Sprite.RotationStyle.ALL_AROUND,
    costumeNumber: 9,
    size: 90,
    visible: false,
    layerOrder: 49,
  }),
  Cursor: new Cursor({
    x: -38,
    y: 180,
    direction: 90,
    rotationStyle: Sprite.RotationStyle.ALL_AROUND,
    costumeNumber: 1,
    size: 100,
    visible: true,
    layerOrder: 95,
  }),
  Bluefishingpole: new Bluefishingpole({
    x: 36,
    y: 28,
    direction: 90,
    rotationStyle: Sprite.RotationStyle.ALL_AROUND,
    costumeNumber: 2,
    size: 100,
    visible: false,
    layerOrder: 50,
  }),
  Sprite1: new Sprite1({
    x: 36,
    y: 28,
    direction: 90,
    rotationStyle: Sprite.RotationStyle.ALL_AROUND,
    costumeNumber: 1,
    size: 100,
    visible: true,
    layerOrder: 51,
  }),
  ScreenShot20210402At2: new ScreenShot20210402At2({
    x: 0,
    y: 0,
    direction: 90,
    rotationStyle: Sprite.RotationStyle.ALL_AROUND,
    costumeNumber: 1,
    size: 100,
    visible: false,
    layerOrder: 52,
  }),
};

const project = new Project(stage, sprites, {
  frameRate: 30, // Set to 60 to make your project run faster
});
export default project;
